# Generated by Django 6.0.3 on 2026-03-22 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255, verbose_name='Название сервиса')),
                ('reason', models.TextField(blank=True, verbose_name='Причина запроса')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрено'), ('rejected', 'Отказано')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_app.telegramuser', verbose_name='Telegram-пользователь')),
            ],
            options={
                'verbose_name': 'Запрос доступа',
                'verbose_name_plural': 'Запросы доступа',
            },
        ),
    ]
